List<String> learningQuotes = [
  "Tell me and I forget, teach me and I may remember, involve me and I learn.",
  "Live as if you were to die tomorrow. Learn as if you were to live forever",
  "For the things we have to learn before we can do them, we learn by doing them",
  "I am always doing that which I cannot do, in order that I may learn how to do it.",
  "Learn as if you were not reaching your goal and as though you were scared of missing it",
  "The beautiful thing about learning is that nobody can take it away from you.",
  "Anyone who stops learning is old, whether at twenty or eighty. Anyone who keeps learning stays young",
  "Intellectual growth should commence at birth and cease only at death.",
  "For the best return on your money, pour your purse into your head.",
  "Learning never exhausts the mind.",
];
List<String> loveQuotes = [
  "Loved you yesterday, love you still, always have, always will.",
  "Thinking of you keeps me awake. Dreaming of you keeps me asleep. Being with you keeps me alive.",
  "If you live to be a hundred, I want to live to be a hundred minus one day so I never have to live without you.",
  "A man is already halfway in love with any woman who listens to him.",
  "Women are meant to be loved, not to be understood.",
  "You make me want to be a better man.",
  "Thinking of you keeps me awake. Dreaming of you keeps me asleep. Being with you keeps me alive.",
  "He is not a lover who does not love forever.",
  "Pleasure of love lasts but a moment. Pain of love lasts a lifetime.",
  "Love is so short, forgetting is so long.",
];
List<String> motivationalQuotes = [
  "Inspiration does exist, but it must find you working.",
  "Show up, show up, show up, and after a while the muse shows up, too.",
  "Don't bunt. Aim out of the ballpark. Aim for the company of immortals.",
  "I have stood on a mountain of no’s for one yes.",
  "If there is no struggle, there is no progress.",
  "Courage is like a muscle. We strengthen it by use.",
  "If the highest aim of a captain were to preserve his ship, he would keep it in port forever.",
  "Keep a little fire burning; however small, however hidden.",
  "The only way of discovering the limits of the possible is to venture a little way past them into the impossible.",
  "Worry is a misuse of imagination.",
];
List<String> truthQuotes = [
  "The truth will set you free. But not until it is finished with you.",
  "Many a doctrine is like a window pane. We see truth through it but it divides us from truth.",
  "Beauty is truth’s smile when she beholds her own face in a perfect mirror.",
  "Honesty is the first chapter in the book of wisdom.",
  "If you want to have a healthy mind, you must feed your mind with truth.",
  "Once you eliminate the impossible, whatever remains, no matter how improbable, must be the truth.",
  "Three things cannot be long hidden: the sun, the moon, and the truth.",
  "Truth is like the sun. You can shut it out for a time, but it ain’t goin’ away.",
  "Every mind must make its choice between truth and repose. It cannot have both.",
  "Truth will always be truth, regardless of lack of understanding, disbelief or ignorance.",
];
